export const clothes = [
    { id: '1', category: '아우터', name: '환절기 코트' },
    { id: '2', category: '아우터', name: '겨울 코트' },
    { id: '3', category: '아우터', name: '패딩' },
    { id: '4', category: '아우터', name: '자켓' },
    { id: '5', category: '아우터', name: '가디건' },
    { id: '6', category: '아우터', name: '베스트' },
    { id: '7', category: '상의', name: '니트' },
    { id: '8', category: '상의', name: '후드' },
    { id: '9', category: '상의', name: '맨투맨' },
    { id: '10', category: '상의', name: '긴소매 티셔츠' },
    { id: '11', category: '상의', name: '셔츠' },
    { id: '12', category: '하의', name: '청바지' },
    { id: '13', category: '하의', name: '반바지' },
    { id: '14', category: '하의', name: '레깅스' },
    { id: '15', category: '하의', name: '면바지' },
    { id: '16', category: '하의', name: '트레이닝 바지' },
    { id: '17', category: '원피스', name: '원피스' },
    { id: '18', category: '기타', name: '우산' },
]